### ISSUE TITLE
JobChuckDispatcher 下没有触发dispatchOnJobSuccess

### ISSUE THREAD

**Issue by kongnanlive** [leobert-lan/Maat#1]
chunk.move2NextChunk()?.let {cc->
为空的时候未处理

**Comment by kongnanlive** [comment]
我感觉FinishEmitter跟emitSuccessAfterInitBlock设计的有点low，不知作者有没有高大上的想法。

**Comment by leobert-lan** [comment]
可否提供一下任务图。

emitSuccessAfterInitBlock，是因为最开始没打算提供手动控制，后续发现确实不太好，推翻重新实现也不太好，就简单提供了一个控制机制。如果有比较好的思路欢迎提出见解，能提pr就更棒了。

基于chunk的调度这周我抽空检查下。

**Comment by leobert-lan** [comment]
thanks！使用JobChunkDispatcher时，所有任务完成后，没有得到预期的成功回调：`maat.callback?.onSuccess?.invoke(maat)`,
已经修复。将直接作为1.1.1版本发布
